name: Go build (reusable workflow)

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        default: false
      service_version:
        type: string
        required: true

env:
  DOCKER_BUILDKIT: 1
  IMAGE_TAG: ${{ vars.ECR_URL }}/${{ vars.SERVICE_NAME }}:${{ inputs.service_version }}

jobs:
  build-publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write # https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-permissions-settings
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test
        run: |
          set -euo pipefail
          docker build . --target build --tag test_build
          docker run --entrypoint sh test_build -c "go test ./..."

      - name: Configure AWS credentials from OIDC
        if: ${{ inputs.publish }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ECR_AWS_ROLE_ARN }}
          aws-region: ${{ vars.ECR_AWS_REGION }}

      - name: Login to Amazon ECR
        if: ${{ inputs.publish }}
        run: |
          aws ecr get-login-password --region "${{ vars.ECR_AWS_REGION }}" | docker login --username AWS --password-stdin "${{ vars.ECR_URL }}"

      - name: Publish
        if: ${{ inputs.publish }}
        run: |
          docker build . --tag "${IMAGE_TAG}" \
            --label "org.opencontainers.image.vendor=Bolt Financial, Inc." \
            --label "org.opencontainers.image.title=${{ vars.SERVICE_NAME }}" \
            --label "org.opencontainers.image.version=${{ inputs.service_version }}" \
            --label "org.opencontainers.image.source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            --label "org.opencontainers.image.revision=${GITHUB_SHA}" \
            --label "org.opencontainers.image.authors=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/attempts/${GITHUB_RUN_ATTEMPT}" \
            --label "org.opencontainers.image.created=$(TZ=UTC date -Iseconds)"

          docker push "${IMAGE_TAG}"
