name: pre-deploy
on:
  workflow_call:
    inputs:
      version:
        description: 'Version of the app'
        required: true
jobs:
  pre-deploy:
    outputs:
      version: ${{ steps.compute-version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shallow
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compute Version
        id: compute-version
        uses: actionsci/compute-semver@1.0.1
        with:
          version: ${{ github.event.inputs.version }}
      - name: Set Outputs
        run: echo "VERSION=${{ steps.compute-version.outputs.version }}" >> $GITHUB_ENV
      - name: Print Version
        run: echo "Version is ${{ steps.compute-version.outputs.version }}"